Mark node as done once we are done with it

diff --git a/pre-build-job.yml b/pre-build-job.yml
--- a/pre-build-job.yml
+++ b/pre-build-job.yml
@@ -38,4 +38,16 @@
             done
             sshopts="-t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root"
             ssh_cmd="ssh $sshopts $CICO_hostname"
-            $ssh_cmd {script_path}
+            $ssh_cmd yum -y install rsync
+            rsync -e "ssh $sshopts" -Ha $(pwd)/ $CICO_hostname:payload
+            $ssh_cmd -t "cd payload && {script_path}"
+            rtn_code=$?
+
+            if [ $rtn_code -eq 0 ]; then
+              rsync -e "ssh $sshopts" -Ha $CICO_hostname:payload $(pwd)/
+              cico node done $CICO_ssid
+            else
+              # fail mode gives us 12 hrs to debug the machine
+              curl "http://admin.ci.centos.org:8080/Node/fail?key=$CICO_API_KEY&ssid=$CICO_ssid"
+            fi
+            exit $rtn_code
